
-- Creacion del usuario

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER SISTVENTAS IDENTIFIED BY admin;


-- Asignar recursos al usuario SISTVENTAS

GRANT CONNECT, RESOURCE TO SISTVENTAS;

-- Crear tabla

DROP TABLE SISTVENTAS.PRODUCTO;

CREATE TABLE SISTVENTAS.PRODUCTO(
    IDPRODUCTO NUMBER(10,0) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    IDCATEGORIA NUMBER(10,0) NOT NULL,
    CONSTRAINT FK_PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCATEGORIA)
    REFERENCES MAESTROS.CATEGORIA
);




